version: '3.8'

services:
  piston:
    image: ghcr.io/engineer-man/piston:latest
    platform: linux/amd64
    ports:
      - "2000:2000"
    restart: unless-stopped
    volumes:
      - ./piston-data:/app/isolate
