spring:
  application:
    name: dsa_training_system
  datasource:
    url: jdbc:mysql://localhost:3306/dsa_training_system_db_demo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    password: 1234
    username: root
  flyway:
    locations: classpath:db/migration
    enabled: true

server:
  port: 8000
