spring:
  application:
    name: dsa_training_system
  datasource:
    url: jdbc:mysql://localhost:3306/dsa_training_system_db_demo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    password: 1234
    username: root
  flyway:
    locations: classpath:db/migration
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/public-key.pem
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ADDRESS}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: dsa_training_system_group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 60s

logging:
  level:
    org.apache.tomcat.util.http.parser.Cookie: DEBUG

github:
  client_id: Ov23li0lgHoq3nu5EIX0
  client_secret: 73a0f5f1099d5392988d36bb67a2523d638ee7c7

google:
  client_id: 250553713111-c3asc7bjbo4qmggcsc5j66tq3b0o4cta.apps.googleusercontent.com

aws:
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  s3_bucket_name: ${AWS_S3_BUCKET_NAME}

file:
  max_size: 5242880

piston:
  load_balancer: ${PISTON_LOAD_BALANCER}
  port: ${PISTON_PORT}

page:
  size: 6

jwt:
  expiration:
    access_token: 1800      # 30 phút = 1800 giây
    refresh_token: 604800   # 7 ngày = 604800 giây (như bạn đang để)

server:
  port: 8000
  address: localhost




