INSERT INTO tags (name) VALUES
    ('Career'),
    ('Feedback'),
    ('Interview'),
    ('Compensation');

INSERT INTO tags (name) VALUES
    ('Greedy'),
    ('Backtracking'),
    ('Recursion'),
    ('Depth-First Search'),
    ('Breadth-First Search'),
    ('Graph'),
    ('Tree'),
    ('Binary Tree'),
    ('Binary Search Tree'),
    ('Heap'),
    ('Stack'),
    ('Queue'),
    ('Priority Queue'),
    ('Linked List'),
    ('Hash Table'),
    ('Set'),
    ('Map'),
    ('Sliding Window'),
    ('Two Pointers'),
    ('Bit Manipulation'),
    ('Prefix Sum'),
    ('Union Find'),
    ('Topological Sort'),
    ('Trie'),
    ('Segment Tree'),
    ('Fenwick Tree'),
    ('Monotonic Stack'),
    ('Line Sweep'),
    ('Divide and Conquer'),
    ('Memoization'),
    ('Tabulation'),
    ('Shortest Path'),
    ('Dijkstra'),
    ('Bellman-Ford'),
    ('Floyd-Warshall'),
    ('Minimum Spanning Tree'),
    ('Kruskal'),
    ('Prim'),
    ('Number Theory'),
    ('Modular Arithmetic'),
    ('Combinatorics'),
    ('Math'),
    ('Geometry'),
    ('Probability'),
    ('Game Theory'),
    ('Simulation'),
    ('Array'),
    ('Randomized Algorithms');

INSERT INTO tags (name) VALUES
    ('JavaScript'),
    ('C'),
    ('C++');